"""
Generates a structured pediatrician referral packet.
Combines CV screening Z-scores with M-CHAT-R results into a single
clinician-readable document following AAP referral guidelines.
"""

from fpdf import FPDF
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, List


REFERRAL_DIR = Path("reports")
REFERRAL_DIR.mkdir(exist_ok=True)


class ReferralPDF(FPDF):
    """Custom PDF class with clinical header/footer."""

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, "AUTISENSE — Developmental Screening Referral Support Document", align="C")
        self.ln(4)
        self.set_draw_color(0, 172, 193)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 4, "CONFIDENTIAL — For clinical use only", align="C")
        self.ln()
        self.cell(
            0, 4,
            "This document is generated by an adjunctive screening tool and does not constitute a clinical diagnosis.",
            align="C"
        )
        self.ln()
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")


class ReferralGenerator:
    """Builds a comprehensive referral packet PDF."""

    def __init__(self):
        self.pdf = None

    def generate_referral(
        self,
        subject_id: str = "Anonymous",
        subject_age_months: Optional[int] = None,
        cv_assessment=None,
        mchat_result=None,
        combined_summary: Optional[Dict] = None,
        face_stats: Optional[Dict] = None,
        session_info: Optional[Dict] = None,
    ) -> str:
        """
        Generate the referral PDF and return the file path.
        """
        self.pdf = ReferralPDF()
        self.pdf.alias_nb_pages()
        self.pdf.set_auto_page_break(auto=True, margin=25)
        self.pdf.add_page()

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        ref_id = f"REF-{int(datetime.now().timestamp())}"

        # ── Patient & Session Info ──
        self._section_header("PATIENT & SESSION INFORMATION")
        info_rows = [
            ("Referral ID", ref_id),
            ("Subject ID", subject_id),
            ("Screening Date", timestamp),
        ]
        if subject_age_months:
            info_rows.append(("Age (months)", str(subject_age_months)))
        if session_info:
            info_rows.append(("Session Duration", f"{session_info.get('duration', 0):.0f} seconds"))
            info_rows.append(("Camera Mode", session_info.get('camera_mode', 'Single')))

        for label, value in info_rows:
            self._info_row(label, value)
        self.pdf.ln(4)

        # ── CV Screening Results ──
        if cv_assessment is not None:
            self._section_header("COMPUTER VISION SCREENING RESULTS")

            risk_level = getattr(cv_assessment, 'risk_level', 'N/A')
            self._info_row("Overall Risk Profile", risk_level)
            self.pdf.ln(2)

            # Domain scores
            domain_scores = getattr(cv_assessment, 'domain_scores', {})
            if domain_scores:
                self.pdf.set_font("Helvetica", "B", 9)
                self.pdf.set_fill_color(240, 248, 255)
                self.pdf.cell(80, 7, "Domain", border=1, fill=True)
                self.pdf.cell(30, 7, "Z-Score", border=1, fill=True, align="C")
                self.pdf.cell(40, 7, "Classification", border=1, fill=True, align="C")
                self.pdf.cell(40, 7, "DSM-5 Code", border=1, fill=True, align="C")
                self.pdf.ln()

                self.pdf.set_font("Helvetica", "", 9)
                for domain_name, score_data in domain_scores.items():
                    z = score_data if isinstance(score_data, (int, float)) else score_data.get('z_score', 0)
                    classification = self._classify_z(z)
                    dsm5 = self._domain_to_dsm5(domain_name)

                    self.pdf.cell(80, 6, domain_name[:38], border=1)
                    self.pdf.cell(30, 6, f"{z:+.1f} SD", border=1, align="C")
                    self.pdf.cell(40, 6, classification, border=1, align="C")
                    self.pdf.cell(40, 6, dsm5, border=1, align="C")
                    self.pdf.ln()

            self.pdf.ln(2)

            # Deviations detail
            deviations = getattr(cv_assessment, 'deviations', [])
            if deviations:
                self.pdf.set_font("Helvetica", "B", 9)
                self.pdf.cell(0, 7, "Detailed Deviation Analysis:", ln=True)
                self.pdf.set_font("Helvetica", "", 8)
                for dev in deviations:
                    z_val = getattr(dev, 'z_score', 0)
                    name = getattr(dev, 'domain_name', 'Unknown')
                    interp = getattr(dev, 'interpretation', '')
                    sig = getattr(dev, 'clinical_significance', 'typical')
                    bullet = "▲" if sig == "atypical" else "●" if sig == "borderline" else "○"
                    self.pdf.multi_cell(
                        0, 5,
                        f"  {bullet} {name} ({z_val:+.1f} SD) — {interp}"
                    )
                self.pdf.ln(2)

        # ── M-CHAT-R Results ──
        if mchat_result is not None:
            self._section_header("M-CHAT-R/F PARENT QUESTIONNAIRE RESULTS")
            self._info_row("Total Score", f"{mchat_result.total_score}/20")
            self._info_row("Risk Level", mchat_result.risk_level)
            self._info_row(
                "Critical Items Failed",
                f"{len(mchat_result.critical_items_flagged)}/6 "
                f"(Items: {', '.join(str(i) for i in mchat_result.critical_items_flagged) or 'None'})"
            )
            self.pdf.ln(2)

            if mchat_result.risk_items:
                self.pdf.set_font("Helvetica", "B", 9)
                self.pdf.cell(0, 6, "At-Risk Items:", ln=True)
                self.pdf.set_font("Helvetica", "", 8)

                from modules.mchat import MCHAT_QUESTIONS
                for qid in mchat_result.risk_items:
                    q = next((q for q in MCHAT_QUESTIONS if q["id"] == qid), None)
                    if q:
                        critical_tag = " [CRITICAL]" if q["critical"] else ""
                        self.pdf.multi_cell(
                            0, 5,
                            f"  Q{qid}{critical_tag} ({q['domain']}): {q['text']}"
                        )
            self.pdf.ln(2)

        # ── Combined Assessment ──
        if combined_summary is not None:
            self._section_header("COMBINED MULTI-MODAL RISK ASSESSMENT")
            self._info_row("Combined Risk Level", combined_summary.get("combined_risk", "N/A"))
            self._info_row("Concordance", combined_summary.get("concordance", "N/A"))
            self.pdf.ln(2)

            self.pdf.set_font("Helvetica", "", 9)
            self.pdf.multi_cell(
                0, 5,
                f"Recommendation: {combined_summary.get('combined_recommendation', '')}"
            )
            self.pdf.ln(3)

        # ── Clinical Recommendations ──
        self._section_header("RECOMMENDED NEXT STEPS")
        recommendations = self._build_recommendations(cv_assessment, mchat_result, combined_summary)
        self.pdf.set_font("Helvetica", "", 9)
        for i, rec in enumerate(recommendations, 1):
            self.pdf.multi_cell(0, 5, f"  {i}. {rec}")
            self.pdf.ln(1)

        # ── Suggested Specialist Referrals ──
        self._section_header("SUGGESTED SPECIALIST REFERRALS")
        specialists = self._build_specialist_list(cv_assessment, mchat_result)
        self.pdf.set_font("Helvetica", "", 9)
        for spec in specialists:
            self.pdf.multi_cell(0, 5, f"  • {spec['type']} — {spec['reason']}")
        self.pdf.ln(3)

        # ── Methodology & Disclaimers ──
        self._section_header("METHODOLOGY & LIMITATIONS")
        self.pdf.set_font("Helvetica", "", 7)
        methodology_text = (
            "Computer Vision Screening: Real-time facial landmark tracking via MediaPipe FaceLandmarker "
            "with blendshape analysis, iris-based gaze estimation with head-pose anchoring, and body pose "
            "estimation via MediaPipe PoseLandmarker. Behavioral metrics were computed against published "
            "neurotypical baselines using Z-score standard deviations, clamped to ±4.0 SD. "
            "Protocol follows a structured 90-second active stimulus paradigm modeled on published "
            "eye-tracking and name-call response studies (Jones & Klin 2013, Ozonoff et al. 2010).\n\n"
            "M-CHAT-R/F: The Modified Checklist for Autism in Toddlers, Revised with Follow-Up is a "
            "validated, standardized parent-report screening instrument with established sensitivity "
            "and specificity for ASD risk detection in children aged 16-30 months "
            "(Robins, Fein, & Barton, 2009).\n\n"
            "IMPORTANT DISCLAIMER: This document is generated by an adjunctive screening tool. "
            "It does NOT constitute a clinical diagnosis. Autism Spectrum Disorder can only be "
            "diagnosed by a qualified professional using comprehensive evaluation instruments "
            "such as the ADOS-2 and ADI-R. This referral support document is intended to assist "
            "clinical decision-making, not replace it."
        )
        self.pdf.multi_cell(0, 4, methodology_text)

        # ── Save ──
        filename = f"referral_{ref_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = str(REFERRAL_DIR / filename)
        self.pdf.output(filepath)
        return filepath

    # ─── HELPER METHODS ───

    def _section_header(self, title: str):
        self.pdf.set_font("Helvetica", "B", 11)
        self.pdf.set_text_color(0, 90, 120)
        self.pdf.cell(0, 8, title, ln=True)
        self.pdf.set_draw_color(0, 172, 193)
        self.pdf.set_line_width(0.3)
        self.pdf.line(10, self.pdf.get_y(), 200, self.pdf.get_y())
        self.pdf.ln(3)
        self.pdf.set_text_color(0, 0, 0)

    def _info_row(self, label: str, value: str):
        self.pdf.set_font("Helvetica", "B", 9)
        self.pdf.cell(60, 6, f"{label}:")
        self.pdf.set_font("Helvetica", "", 9)
        self.pdf.cell(0, 6, value, ln=True)

    def _classify_z(self, z: float) -> str:
        z_abs = abs(z)
        if z_abs < 1.0:
            return "Typical"
        elif z_abs < 2.0:
            return "Borderline"
        elif z_abs < 3.0:
            return "Elevated"
        else:
            return "Clinically Significant"

    def _domain_to_dsm5(self, domain_name: str) -> str:
        mapping = {
            "eye_contact": "A.2",
            "social_preference": "A.1",
            "social_visual": "A.1",
            "name_call": "A.1",
            "name_response": "A.1",
            "emotional_reciprocity": "A.2",
            "smile": "A.2",
            "motor_stereotypy": "B.1",
            "repetitive": "B.1",
            "gaze_stability": "A.2",
            "flat_affect": "A.1",
        }
        name_lower = domain_name.lower().replace(" ", "_")
        for key, code in mapping.items():
            if key in name_lower:
                return code
        return "—"

    def _build_recommendations(self, cv_assessment, mchat_result, combined_summary) -> List[str]:
        recs = []

        combined_risk = "LOW"
        if combined_summary:
            combined_risk = combined_summary.get("combined_risk", "LOW")
        elif mchat_result:
            combined_risk = mchat_result.risk_level
        elif cv_assessment:
            combined_risk = getattr(cv_assessment, 'risk_level', 'Typical')

        if combined_risk in ("HIGH", "High", "Elevated"):
            recs.extend([
                "Refer for comprehensive developmental evaluation (ADOS-2/ADI-R)",
                "Refer for audiological evaluation to rule out hearing impairment",
                "Initiate early intervention services — do not wait for formal diagnosis",
                "Connect family with state Early Intervention (Part C) program",
                "Refer to speech-language pathologist for communication assessment",
                "Schedule follow-up appointment within 30 days to confirm referral completion",
                "Provide family with educational materials about developmental differences",
            ])
        elif combined_risk in ("MEDIUM", "Medium", "Borderline"):
            recs.extend([
                "Administer M-CHAT-R/F Follow-Up interview on flagged items (if not yet done)",
                "Consider referral for developmental evaluation based on clinical judgment",
                "Monitor developmental milestones closely at subsequent visits",
                "Rescreen with M-CHAT-R at next well-child visit (within 3-6 months)",
                "Discuss developmental observations with family using strengths-based approach",
                "Consider speech/language screening if communication concerns are present",
            ])
        else:
            recs.extend([
                "No immediate referral indicated based on current screening results",
                "Continue routine developmental surveillance at all well-child visits",
                "If child < 24 months, repeat M-CHAT-R screening at 24-month visit",
                "Remain responsive to any future parental concerns about development",
            ])

        return recs

    def _build_specialist_list(self, cv_assessment, mchat_result) -> List[Dict]:
        specialists = []

        # Always recommend primary evaluation path
        specialists.append({
            "type": "Developmental Pediatrician",
            "reason": "Comprehensive neurodevelopmental evaluation and differential diagnosis",
        })

        flagged_domains = set()

        if mchat_result and hasattr(mchat_result, 'flagged_domains'):
            for d in mchat_result.flagged_domains:
                flagged_domains.add(d.lower())

        if cv_assessment:
            domain_scores = getattr(cv_assessment, 'domain_scores', {})
            for name, val in domain_scores.items():
                z = val if isinstance(val, (int, float)) else val.get('z_score', 0)
                if abs(z) >= 1.5:
                    flagged_domains.add(name.lower())

        # Map domains to specialists
        speech_triggers = {
            "name response", "receptive language", "requesting", "joint attention",
            "social reciprocity", "name_call", "social_preference",
        }
        ot_triggers = {
            "sensory sensitivity", "sensory processing", "motor development",
            "motor_stereotypy", "repetitive behaviors",
        }
        psych_triggers = {
            "social interest", "eye contact", "imitation", "social referencing",
            "showing / sharing", "attention seeking", "imaginative play",
            "emotional_reciprocity", "flat_affect",
        }

        if flagged_domains & speech_triggers:
            specialists.append({
                "type": "Speech-Language Pathologist (SLP)",
                "reason": "Communication, receptive/expressive language, and social communication assessment",
            })

        if flagged_domains & ot_triggers:
            specialists.append({
                "type": "Occupational Therapist (OT)",
                "reason": "Sensory processing, motor development, and adaptive behavior assessment",
            })

        if flagged_domains & psych_triggers:
            specialists.append({
                "type": "Child Psychologist (ASD specialty)",
                "reason": "Social-emotional development, behavioral assessment, and ADOS-2 administration",
            })

        # Audiologist if auditory/name response flagged
        audio_triggers = {"auditory response", "name response", "name_call"}
        if flagged_domains & audio_triggers:
            specialists.append({
                "type": "Audiologist",
                "reason": "Comprehensive hearing evaluation to rule out auditory impairment",
            })

        # BCBA if repetitive behaviors flagged
        bcba_triggers = {"repetitive behaviors", "motor_stereotypy"}
        if flagged_domains & bcba_triggers:
            specialists.append({
                "type": "Board Certified Behavior Analyst (BCBA)",
                "reason": "Functional behavior assessment and behavior intervention planning",
            })

        return specialists