# modules/report_generator.py

import time
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from fpdf import FPDF
from PIL import Image

from config import REPORTS_DIR, ASSETS_DIR


class DiagnosticReportPDF(FPDF):
    """
    Custom PDF class for the Autism Screening
    Diagnostic Evidence Report.
    """

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        """Page header with branding."""
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(
            0, 8,
            'NeuroLens AI | Behavioral Screening Report',
            align='L'
        )
        self.cell(
            0, 8,
            f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}',
            align='R',
            new_x="LMARGIN", new_y="NEXT"
        )
        # Separator line
        self.set_draw_color(41, 128, 185)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        """Page footer with disclaimer."""
        self.set_y(-25)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(150, 150, 150)
        self.multi_cell(
            0, 3,
            "DISCLAIMER: This report is generated by an AI-based "
            "screening tool for research and preliminary assessment "
            "purposes only. It does NOT constitute a clinical "
            "diagnosis. All findings must be reviewed and validated "
            "by a qualified healthcare professional. "
            "Not for use as sole diagnostic criteria.",
            align='C'
        )
        self.set_font('Helvetica', 'I', 8)
        self.cell(
            0, 5,
            f'Page {self.page_no()}/{{nb}}',
            align='C'
        )


class ReportGenerator:
    """
    Generates a comprehensive PDF diagnostic report
    from the RiskAssessment data.

    The report includes:
    1. Patient/Session Info
    2. Executive Summary
    3. Risk Score Dashboard
    4. Domain-by-Domain Analysis
    5. Visual Evidence Timeline (screenshots)
    6. Detailed Evidence Log
    7. Recommendations
    8. Technical Methodology
    """

    def __init__(self):
        self.pdf = None

    def _add_title_page(
        self,
        pdf: DiagnosticReportPDF,
        session_info: dict
    ):
        """Create the title/cover page."""
        pdf.add_page()

        # Title
        pdf.ln(30)
        pdf.set_font('Helvetica', 'B', 28)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(
            0, 15, 'Behavioral Screening Report',
            align='C', new_x="LMARGIN", new_y="NEXT"
        )

        pdf.set_font('Helvetica', '', 14)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(
            0, 10, 'AI-Assisted Autism Spectrum Screening',
            align='C', new_x="LMARGIN", new_y="NEXT"
        )

        pdf.ln(20)

        # Session info box
        pdf.set_fill_color(240, 248, 255)
        pdf.set_draw_color(41, 128, 185)
        box_x = 40
        box_y = pdf.get_y()
        box_w = 130
        box_h = 60
        pdf.rect(box_x, box_y, box_w, box_h, style='DF')

        pdf.set_xy(box_x + 5, box_y + 5)
        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(box_w - 10, 8, 'SESSION DETAILS')
        pdf.ln(10)

        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)

        details = [
            (
                "Session ID",
                session_info.get(
                    'session_id',
                    f"SCR-{int(time.time())}"
                )
            ),
            (
                "Date",
                datetime.now().strftime("%B %d, %Y at %H:%M")
            ),
            (
                "Duration",
                f"{session_info.get('duration', 0):.0f} seconds"
            ),
            (
                "Camera Mode",
                session_info.get('camera_mode', 'Single')
            ),
            (
                "Subject ID",
                session_info.get('subject_id', 'Anonymous')
            ),
        ]

        for label, value in details:
            pdf.set_x(box_x + 10)
            pdf.set_font('Helvetica', 'B', 9)
            pdf.cell(35, 7, f"{label}:")
            pdf.set_font('Helvetica', '', 9)
            pdf.cell(80, 7, str(value))
            pdf.ln(7)

        pdf.ln(30)

        # Risk Level Banner
        risk_level = session_info.get('risk_level', 'Unknown')
        risk_score = session_info.get('risk_score', 0)

        if risk_level == "Low":
            banner_color = (46, 204, 113)     # Green
        elif risk_level == "Moderate":
            banner_color = (241, 196, 15)     # Yellow
        elif risk_level == "High":
            banner_color = (231, 76, 60)      # Red
        else:
            banner_color = (192, 57, 43)      # Dark Red

        pdf.set_fill_color(*banner_color)
        banner_y = pdf.get_y()
        pdf.rect(30, banner_y, 150, 25, style='F')

        pdf.set_xy(30, banner_y + 3)
        pdf.set_font('Helvetica', 'B', 18)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(
            150, 10,
            f'RISK LEVEL: {risk_level.upper()}',
            align='C',
            new_x="LMARGIN", new_y="NEXT"
        )
        pdf.set_xy(30, banner_y + 14)
        pdf.set_font('Helvetica', '', 11)
        pdf.cell(
            150, 8,
            f'Overall Score: {risk_score}/100',
            align='C'
        )



    def _add_executive_summary(
        self,
        pdf: DiagnosticReportPDF,
        assessment
    ):
        """Add executive summary with clinical deviations."""
        pdf.add_page()

        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(
            0, 10, '1. Clinical Deviation Analysis',
            new_x="LMARGIN", new_y="NEXT"
        )
        pdf.ln(3)

        # Summary text
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 6, assessment.summary)
        pdf.ln(8)

        # Deviation Table
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(
            0, 8, 'Behavioral Domain Deviations',
            new_x="LMARGIN", new_y="NEXT"
        )
        pdf.ln(3)

        # Table header
        pdf.set_fill_color(41, 128, 185)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 8)
        pdf.cell(42, 7, 'Domain', fill=True, border=1)
        pdf.cell(22, 7, 'DSM-5', fill=True, border=1, align='C')
        pdf.cell(20, 7, 'Value', fill=True, border=1, align='C')
        pdf.cell(28, 7, 'Baseline', fill=True, border=1, align='C')
        pdf.cell(18, 7, 'Z-Score', fill=True, border=1, align='C')
        pdf.cell(22, 7, 'Status', fill=True, border=1, align='C')
        pdf.cell(38, 7, 'Interpretation', fill=True, border=1, align='C')
        pdf.ln()

        # Table rows
        if hasattr(assessment, 'deviations'):
            for dev in assessment.deviations:
                pdf.set_font('Helvetica', '', 7)
                pdf.set_text_color(50, 50, 50)

                # Status color
                if dev.clinical_significance == "atypical":
                    status_color = (231, 76, 60)
                    status_label = "ATYPICAL"
                elif dev.clinical_significance == "borderline":
                    status_color = (241, 196, 15)
                    status_label = "BORDER"
                else:
                    status_color = (46, 204, 113)
                    status_label = "TYPICAL"

                # Row
                fill = False
                pdf.cell(
                    42, 6, f"  {dev.domain_name[:22]}",
                    border=1, fill=fill
                )
                pdf.cell(
                    22, 6, dev.dsm5_code[:10],
                    border=1, align='C', fill=fill
                )

                # Value
                if dev.metric_value == -1:
                    val_str = "N/R"  # No response
                elif dev.metric_value < 1:
                    val_str = f"{dev.metric_value:.4f}"
                else:
                    val_str = f"{dev.metric_value:.1f}"
                pdf.cell(
                    20, 6, val_str,
                    border=1, align='C', fill=fill
                )

                # Baseline
                if dev.baseline_std > 0:
                    bl_str = (
                        f"{dev.baseline_mean:.1f}"
                        f"+-{dev.baseline_std:.1f}"
                    )
                else:
                    bl_str = "-"
                pdf.cell(
                    28, 6, bl_str,
                    border=1, align='C', fill=fill
                )

                # Z-score
                pdf.set_font('Helvetica', 'B', 8)
                z_str = f"{dev.z_score:+.1f} SD"
                pdf.cell(
                    18, 6, z_str,
                    border=1, align='C', fill=fill
                )

                # Status badge
                pdf.set_fill_color(*status_color)
                pdf.set_text_color(255, 255, 255)
                pdf.set_font('Helvetica', 'B', 7)
                pdf.cell(
                    22, 6, status_label,
                    border=1, align='C', fill=True
                )

                # Brief interpretation
                pdf.set_fill_color(245, 245, 245)
                pdf.set_text_color(80, 80, 80)
                pdf.set_font('Helvetica', '', 6)
                short_interp = dev.interpretation[:45]
                if len(dev.interpretation) > 45:
                    short_interp += "..."
                pdf.cell(
                    38, 6, short_interp,
                    border=1, fill=fill
                )
                pdf.ln()

        pdf.ln(8)

        # Deviation chart (visual bars showing z-scores)
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(
            0, 8, 'Deviation Profile (Standard Deviations)',
            new_x="LMARGIN", new_y="NEXT"
        )
        pdf.ln(3)

        if hasattr(assessment, 'deviations'):
            center_x = 120  # Center line (z=0)
            bar_height = 7
            scale = 20  # Pixels per SD

            y_pos = pdf.get_y()

            for dev in assessment.deviations:
                # Label
                pdf.set_xy(10, y_pos)
                pdf.set_font('Helvetica', '', 7)
                pdf.set_text_color(50, 50, 50)
                pdf.cell(50, bar_height, dev.domain_name[:28], align='R')

                # Background (range markers)
                # -3SD to +3SD range
                bg_start = center_x - 3 * scale
                bg_width = 6 * scale
                pdf.set_fill_color(245, 245, 245)
                pdf.rect(
                    bg_start, y_pos,
                    bg_width, bar_height, style='F'
                )

                # Zone colors
                # Typical zone (-1 to +1)
                pdf.set_fill_color(200, 240, 200)
                pdf.rect(
                    center_x - scale, y_pos,
                    2 * scale, bar_height, style='F'
                )

                # Center line
                pdf.set_draw_color(100, 100, 100)
                pdf.set_line_width(0.3)
                pdf.line(
                    center_x, y_pos,
                    center_x, y_pos + bar_height
                )

                # Z-score marker
                z_clamped = max(-3.0, min(3.0, dev.z_score))
                marker_x = center_x + z_clamped * scale

                if dev.clinical_significance == "atypical":
                    marker_color = (231, 76, 60)
                elif dev.clinical_significance == "borderline":
                    marker_color = (241, 196, 15)
                else:
                    marker_color = (46, 204, 113)

                pdf.set_fill_color(*marker_color)
                # Draw marker as filled circle
                marker_radius = 3
                pdf.ellipse(
                    marker_x - marker_radius,
                    y_pos + bar_height / 2 - marker_radius,
                    marker_radius * 2,
                    marker_radius * 2,
                    style='F'
                )

                # Z-score label
                pdf.set_xy(center_x + 3 * scale + 3, y_pos)
                pdf.set_font('Helvetica', 'B', 7)
                pdf.cell(
                    15, bar_height,
                    f"{dev.z_score:+.1f}",
                    align='L'
                )

                y_pos += bar_height + 3

            # Scale legend
            y_pos += 5
            pdf.set_xy(10, y_pos)
            pdf.set_font('Helvetica', 'I', 6)
            pdf.set_text_color(120, 120, 120)
            pdf.cell(
                0, 4,
                "Scale: Each unit = 1 Standard Deviation. "
                "Green zone = Typical (-1 to +1 SD). "
                "Markers beyond +-2 SD indicate significant deviation.",
                align='C'
            )

    def _add_evidence_timeline(
        self,
        pdf: DiagnosticReportPDF,
        assessment  # RiskAssessment
    ):
        """
        Add the visual evidence timeline with screenshots
        and explanations. THIS IS THE KILLER FEATURE.
        """
        pdf.add_page()

        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(
            0, 10, '2. Visual Evidence Timeline',
            new_x="LMARGIN", new_y="NEXT"
        )
        pdf.ln(2)

        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(
            0, 5,
            "Each entry below represents a moment during the "
            "screening session where the AI system detected a "
            "behavioral marker. Annotated screenshots provide "
            "visual evidence for clinical review."
        )
        pdf.ln(5)

        if not assessment.evidence_items:
            pdf.set_font('Helvetica', '', 11)
            pdf.set_text_color(46, 204, 113)
            pdf.cell(
                0, 10,
                "No significant behavioral markers were flagged "
                "during this session.",
                align='C'
            )
            return

        # Evidence entries
        for i, evidence in enumerate(assessment.evidence_items):
            # Check if we need a new page
            if pdf.get_y() > 200:
                pdf.add_page()

            # --- Entry Header ---
            # Severity color bar
            if evidence.severity == "high":
                sev_color = (231, 76, 60)
                sev_label = "HIGH"
            elif evidence.severity == "medium":
                sev_color = (241, 196, 15)
                sev_label = "MEDIUM"
            else:
                sev_color = (46, 204, 113)
                sev_label = "LOW"

            entry_y = pdf.get_y()

            # Color strip on left
            pdf.set_fill_color(*sev_color)
            pdf.rect(10, entry_y, 3, 50, style='F')

            # Timestamp and category
            pdf.set_xy(16, entry_y)
            pdf.set_font('Helvetica', 'B', 11)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(
                80, 6,
                f"[{evidence.session_time_str}] "
                f"{evidence.category.upper()}"
            )

            # Severity badge
            pdf.set_fill_color(*sev_color)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font('Helvetica', 'B', 8)
            badge_x = pdf.get_x() + 5
            pdf.set_xy(badge_x, entry_y)
            pdf.cell(
                25, 6, sev_label,
                fill=True, align='C'
            )

            # Confidence
            pdf.set_text_color(100, 100, 100)
            pdf.set_font('Helvetica', '', 8)
            pdf.set_xy(badge_x + 28, entry_y)
            pdf.cell(
                30, 6,
                f"Conf: {evidence.confidence * 100:.0f}%"
            )
            pdf.ln(8)

            # Description
            pdf.set_x(16)
            pdf.set_font('Helvetica', '', 9)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(120, 5, evidence.description)

            # Metric info
            if evidence.metric_name:
                pdf.set_x(16)
                pdf.set_font('Helvetica', 'I', 8)
                pdf.set_text_color(120, 120, 120)

                metric_str = (
                    f"Metric: {evidence.metric_name} = "
                    f"{evidence.metric_value:.1f}"
                )

                if (
                    hasattr(evidence, 'z_score')
                    and evidence.z_score != 0
                ):
                    metric_str += (
                        f" (z={evidence.z_score:+.1f} SD"
                    )
                    if (
                        hasattr(evidence, 'baseline_mean')
                        and evidence.baseline_mean > 0
                    ):
                        metric_str += (
                            f", baseline: "
                            f"{evidence.baseline_mean:.1f}"
                            f"+-{evidence.baseline_std:.1f}"
                        )
                    metric_str += ")"
                elif hasattr(evidence, 'threshold_value'):
                    metric_str += (
                        f" (threshold: "
                        f"{evidence.threshold_value:.1f})"
                    )

                pdf.cell(120, 4, metric_str)
                pdf.ln(5)

            # Screenshot (if available)
            if (
                evidence.screenshot_path
                and os.path.exists(evidence.screenshot_path)
            ):
                try:
                    img_x = 140
                    img_y = entry_y + 2
                    img_w = 55

                    # Check image is valid
                    img = Image.open(evidence.screenshot_path)
                    img_h = (img.size[1] / img.size[0]) * img_w

                    pdf.image(
                        evidence.screenshot_path,
                        x=img_x, y=img_y,
                        w=img_w
                    )

                    # Image border
                    pdf.set_draw_color(*sev_color)
                    pdf.set_line_width(0.5)
                    pdf.rect(
                        img_x, img_y,
                        img_w, img_h
                    )
                except Exception as e:
                    pdf.set_xy(140, entry_y + 5)
                    pdf.set_font('Helvetica', 'I', 7)
                    pdf.cell(50, 5, "[Screenshot unavailable]")

            # Separator
            current_y = max(pdf.get_y() + 3, entry_y + 55)
            pdf.set_y(current_y)
            pdf.set_draw_color(220, 220, 220)
            pdf.set_line_width(0.2)
            pdf.line(16, current_y, 195, current_y)
            pdf.ln(5)

    def _add_recommendations(
        self,
        pdf: DiagnosticReportPDF,
        assessment  # RiskAssessment
    ):
        """Add clinical recommendations section."""
        pdf.add_page()

        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(
            0, 10, '3. Recommendations',
            new_x="LMARGIN", new_y="NEXT"
        )
        pdf.ln(5)

        if not assessment.recommendations:
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(0, 8, "No specific recommendations.")
            return

        for i, rec in enumerate(assessment.recommendations):
            pdf.set_fill_color(240, 248, 255)
            rec_y = pdf.get_y()
            pdf.rect(15, rec_y, 180, 15, style='DF')

            # Number circle
            pdf.set_fill_color(41, 128, 185)
            pdf.ellipse(18, rec_y + 2, 10, 10, style='F')
            pdf.set_xy(18, rec_y + 2)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(10, 10, str(i + 1), align='C')

            # Recommendation text
            pdf.set_xy(32, rec_y + 2)
            pdf.set_font('Helvetica', '', 9)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(158, 5, rec)
            pdf.ln(5)

    def _add_methodology(self, pdf: DiagnosticReportPDF):
        """Add technical methodology section."""
        pdf.add_page()

        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(
            0, 10, '4. Technical Methodology',
            new_x="LMARGIN", new_y="NEXT"
        )
        pdf.ln(5)

        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(60, 60, 60)

        methodology_text = """
Clinical Framework & Diagnostic Alignment:
- DSM-5-TR Mapping: System metrics directly quantify criterion A.1 (social-emotional reciprocity), A.2 (nonverbal communicative behaviors), and B.1 (stereotyped motor movements).
- Clinical Precedent: Algorithms are calibrated against behavioral markers established in the Autism Diagnostic Observation Schedule (ADOS-2) and the Autism Diagnostic Interview-Revised (ADI-R).

Computer Vision & Biometric Pipeline:
- Facial Biomarkers: MediaPipe Face Mesh extracts 468 3D spatial landmarks. Iris position vectors are mapped against head-pose (Yaw/Pitch via PnP solving) to accurately calculate Gaze Latency and Eye Contact Avoidance (Ozonoff et al., 2010).
- Micro-Expression Analysis: Flattened affect is quantified using a rolling standard deviation of 11 specific facial blendshapes, measuring deficits in spontaneous emotional expression.
- Motor Stereotypy: 33-point skeletal pose estimation utilizes Digital Signal Processing (DSP). Torso oscillation is processed via zero-crossing rate of a detrended time-series signal to detect rocking frequency (Hz).
- Hand Flapping: Wrist velocity magnitude is combined with direction-reversal frequency to isolate stereotyped stimming behaviors from typical gross motor movements.

Explainable AI (XAI) & Privacy:
- Edge Processing: 100% of video frame processing occurs on the edge device via TensorFlow Lite. No raw video is transmitted, ensuring HIPAA and GDPR compliance.
- Transparent Scoring: The Risk Score is a weighted ensemble algorithm, not a black-box neural network. Every clinical flag generates an auditable, timestamped screenshot and a distinct mathematical threshold.

Limitations & Clinical Disclaimer:
- This system provides quantitative phenotypic telemetry. It does NOT account for intellectual disabilities, global developmental delay, or cultural variances in baseline eye contact.
- Findings must be interpreted strictly as an adjunctive screening mechanism to support pediatric neurologists.
"""
        pdf.multi_cell(0, 4.5, methodology_text.strip())

    def generate_report(
        self,
        assessment,       # RiskAssessment
        session_info: dict,
        face_stats: dict,
        body_stats: Optional[dict] = None
    ) -> str:
        """
        Generate the complete PDF diagnostic report.

        Returns: filepath of the generated PDF
        """
        pdf = DiagnosticReportPDF()
        pdf.alias_nb_pages()

        # 1. Title / Cover Page
        self._add_title_page(pdf, {
            **session_info,
            'risk_level': assessment.risk_level,
            'risk_score': assessment.overall_risk_score
        })

        # 2. Executive Summary + Domain Scores
        self._add_executive_summary(pdf, assessment)

        # 3. Visual Evidence Timeline (THE KILLER FEATURE)
        self._add_evidence_timeline(pdf, assessment)

        # 4. Recommendations
        self._add_recommendations(pdf, assessment)

        # 5. Technical Methodology
        self._add_methodology(pdf)

        # Save PDF
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"NeuroLens_Report_{timestamp}.pdf"
        filepath = REPORTS_DIR / filename
        pdf.output(str(filepath))

        print(f"[ReportGenerator] Report saved: {filepath}")
        return str(filepath)